#=================================================================================#
# LICENSE (MIT)                                                                   #
#=================================================================================#
#                                                                                 #
# The MIT License (MIT)                                                           #
#                                                                                 #
# Copyright (c) 2024 - 2026 luau-project https://github.com/luau-project/lua-uuid #
#                                                                                 #
# Permission is hereby granted, free of charge, to any person obtaining a copy    #
# of this software and associated documentation files (the "Software"), to deal   #
# in the Software without restriction, including without limitation the rights    #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell       #
# copies of the Software, and to permit persons to whom the Software is           #
# furnished to do so, subject to the following conditions:                        #
#                                                                                 #
# The above copyright notice and this permission notice shall be included in all  #
# copies or substantial portions of the Software.                                 #
#                                                                                 #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR      #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,        #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE     #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER          #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,   #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE   #
# SOFTWARE.                                                                       #
#                                                                                 #
#=================================================================================#

# The intent of this Makefile
# is to build and install `lua-uuid`
# through LuaRocks, using variables
# defined by LuaRocks.
# For a feature-complete Makefile,
# take a look at `Makefile.unix`.

__EMPTY =
LUA_DIR = /usr/local
LUA_INCDIR = $(LUA_DIR)/include

LUA_VERSION = 5.1
INSTALL_PREFIX = /usr/local
INSTALL_LIBDIR = $(INSTALL_PREFIX)/lib/lua/$(LUA_VERSION)

CC = cc
CCONLY = -c
CCINCFLAG = -I
CCINCLUDES = $(CCINCFLAG)$(LUA_INCDIR)
CCOUT = -o $(__EMPTY)
CFLAGS_EXTRA = -DLUA_UUID_BUILD_SHARED -DLUA_UUID_USE_APPLE
LIBFLAG_EXTRA = -framework CoreFoundation

# Usually, there is no need
# to edit below this line

OBJ_EXTENSION = o
LIB_EXTENSION = so
LUA_UUID_SHARED_LIB = src/lua-uuid.$(LIB_EXTENSION)
LUA_UUID_SHARED_OBJ = src/lua-uuid.$(OBJ_EXTENSION)
LUA_UUID_SHARED_SRC = src/lua-uuid.c

INSTALL = install
INSTALLPFLAG = -p
INSTALLEXEFLAGS = -m 0755
INSTALLFLAGS = $(INSTALLPFLAG) $(INSTALLEXEFLAGS)

ENV = env
LUA = lua

RM = rm
RMFLAGS = -f

.PHONY: all
all: shared

.PHONY: shared
shared: $(LUA_UUID_SHARED_LIB)

$(LUA_UUID_SHARED_LIB): $(LUA_UUID_SHARED_OBJ)
	$(CC) $(LIBFLAG) $(CCOUT)$(LUA_UUID_SHARED_LIB) $(LUA_UUID_SHARED_OBJ) $(LIBFLAG_EXTRA)

$(LUA_UUID_SHARED_OBJ): $(LUA_UUID_SHARED_SRC)
	$(CC) $(CCONLY) $(CFLAGS_EXTRA) $(CFLAGS) $(CCINCLUDES) $(CCOUT)$(LUA_UUID_SHARED_OBJ) $(LUA_UUID_SHARED_SRC)

.PHONY: install
install:
	$(INSTALL) $(INSTALLFLAGS) $(LUA_UUID_SHARED_LIB) $(INSTALL_LIBDIR)

.PHONY: clean-obj
clean-obj:
	-$(RM) $(RMFLAGS) $(LUA_UUID_SHARED_OBJ)

.PHONY: clean-lib
clean-lib:
	-$(RM) $(RMFLAGS) $(LUA_UUID_SHARED_LIB)

.PHONY: clean
clean: clean-obj clean-lib
