name: CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

permissions: read-all

jobs:
  test-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - 5.5
          - luajit
          - openresty

        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        toolchain:
          - msvc
          - cc

        exclude:
          - os: ubuntu-latest
            toolchain: msvc

          - os: macos-latest
            toolchain: msvc

    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install -y uuid-dev

      - name: Setup MSVC
        uses: step-security/msvc-dev-cmd@22c98154b708dbd743e6f27a933cf6ceba3305c4 # v1.31.1
        if: runner.os == 'Windows' && matrix.toolchain == 'msvc'

      - name: Setup Lua and LuaRocks
        uses: luau-project/setup-lua@59b296b674991ab17ba0550a40a5cda9dbe8ca38 # v2.0.4
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Set environment variable to hold the rockspec name (Unix)
        if: runner.os != 'Windows'
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "ROCKSPEC=$(make -f Makefile.unix echo-rockspec)" >> $GITHUB_ENV
          else
            echo "ROCKSPEC=$(make -f Makefile.unix echo-dev-rockspec)" >> $GITHUB_ENV
          fi

      - name: Set environment variable to hold the rockspec name (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          IF "${{ matrix.toolchain }}" EQU "msvc" (
            SET "MAKE_PROG=nmake"
            SET "MAKE_FILE_FLAG=/F"
          ) ELSE IF "${{ matrix.toolchain }}" EQU "cc" (
            SET "MAKE_PROG=mingw32-make"
            SET "MAKE_FILE_FLAG=-f"
          ) ELSE (
            ECHO Unknown matrix.toolchain: ${{ matrix.toolchain }}
            EXIT /B 1
          )

          IF "${{ github.ref_type }}" EQU "tag" (
            SET "MAKE_TARGET=echo-rockspec"
          ) ELSE (
            SET "MAKE_TARGET=echo-dev-rockspec"
          )

          @FOR /F "TOKENS=* USEBACKQ" %%F IN (`%MAKE_PROG% %MAKE_FILE_FLAG% Makefile.win %MAKE_TARGET%`) ^
          DO @ECHO ROCKSPEC=%%F>>%GITHUB_ENV%

      - name: Lint (Unix)
        if: runner.os != 'Windows'
        run: luarocks lint "$ROCKSPEC"

      - name: Lint (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: luarocks lint "%ROCKSPEC%"

      - name: Build (Unix)
        if: runner.os != 'Windows'
        run: luarocks make "$ROCKSPEC"

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: luarocks make "%ROCKSPEC%"

      - name: Test (Unix)
        if: runner.os != 'Windows'
        run: |
          for f in samples/*.lua; do
            echo "Running sample: ${f}";

            lua "${f}" || {
              echo "Failed to run the sample: ${f}";
              exit 1;
            }
          done

      - name: Test (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          FOR %%F IN (samples\*.lua) DO (
            ECHO Running sample "%%F"
            lua "%%F"

            IF %ERRORLEVEL% NEQ 0 (
              ECHO Failed to run the sample: %%F
              EXIT /B 1
            )
          )