name: CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

permissions: read-all

jobs:
  test-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - 5.5
          - luajit
          - openresty

        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install -y uuid-dev

      - name: Setup Lua and LuaRocks
        uses: luau-project/setup-lua@ebdc724769a3976b27abe70d93a730aede440ba9 # v2.0.8
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Build and test (Unix)
        if: runner.os != 'Windows'
        run: |
          if test "$RUNNER_OS" = "macOS"; then
            makefile="Makefile.macosx"
          else
            makefile="Makefile.unix"
          fi
          make \
            -f "${makefile}" \
            "PREFIX=$(luarocks config variables.LUA_DIR)" \
            "CCOPT=-O0" \
            "LUA_VERSION=$(luarocks config lua_version)" \
            "LUA_INCDIR=$(luarocks config variables.LUA_INCDIR)" \
            "CFLAGS_EXTRA=-fprofile-arcs -ftest-coverage" \
            "LDFLAGS_EXTRA=--coverage" \
            all test

      - name: Build and test (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          @SETLOCAL ENABLEDELAYEDEXPANSION
          @FOR /F "TOKENS=* USEBACKQ" %%D IN (`luarocks config variables.LUA_DIR`) ^
          DO @FOR /F "TOKENS=* USEBACKQ" %%I IN (`luarocks config variables.LUA_INCDIR`) ^
          DO @FOR /F "TOKENS=* USEBACKQ" %%V IN (`luarocks config lua_version`) ^
          DO @FOR /F "TOKENS=* USEBACKQ" %%L IN (`dir /B %%D\lib\liblua*.dll.a`) ^
          DO (
            @SET "_TMP_LUA_LIBNAME=%%L"
            @SET "_LUA_LIBNAME=!_TMP_LUA_LIBNAME:~3,-6!"

            @mingw32-make ^
              -f "Makefile.win" ^
              "PREFIX=%%D" ^
              "CCOPT=-O0" ^
              "LUA_VERSION=%%V" ^
              "LUA_INCDIR=%%I" ^
              "LUA_LIBNAME=!_LUA_LIBNAME!" ^
              "CFLAGS_EXTRA=-fprofile-arcs -ftest-coverage" ^
              "LDFLAGS_EXTRA=--coverage" ^
              all test
          )

      - name: Generate coverage report
        run: gcov --relative-only "src/lua-uuid.c"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test-luarocks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - 5.5
          - luajit
          - openresty

        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        toolchain:
          - msvc
          - cc

        exclude:
          - os: ubuntu-latest
            toolchain: msvc

          - os: macos-latest
            toolchain: msvc

    env:
      TOOLCHAIN: ${{ matrix.toolchain }}

    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install -y uuid-dev

      - name: Setup MSVC
        uses: step-security/msvc-dev-cmd@22c98154b708dbd743e6f27a933cf6ceba3305c4 # v1.31.1
        if: runner.os == 'Windows' && matrix.toolchain == 'msvc'

      - name: Setup Lua and LuaRocks
        uses: luau-project/setup-lua@ebdc724769a3976b27abe70d93a730aede440ba9 # v2.0.8
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Set environment variable to hold the rockspec name (Unix)
        if: runner.os != 'Windows'
        run: |
          if test "$GITHUB_REF_TYPE" = "tag"; then
            echo "ROCKSPEC=$(make -f Makefile.unix echo-rockspec)" >> $GITHUB_ENV
          else
            echo "ROCKSPEC=$(make -f Makefile.unix echo-dev-rockspec)" >> $GITHUB_ENV
          fi

      - name: Set environment variable to hold the rockspec name (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          IF "%TOOLCHAIN%" EQU "msvc" (
            SET "MAKE_PROG=nmake"
            SET "MAKE_FILE_FLAG=/F"
          ) ELSE IF "%TOOLCHAIN%" EQU "cc" (
            SET "MAKE_PROG=mingw32-make"
            SET "MAKE_FILE_FLAG=-f"
          ) ELSE (
            ECHO Unknown matrix.toolchain: %TOOLCHAIN%
            EXIT /B 1
          )

          IF "%GITHUB_REF_TYPE%" EQU "tag" (
            SET "MAKE_TARGET=echo-rockspec"
          ) ELSE (
            SET "MAKE_TARGET=echo-dev-rockspec"
          )

          @FOR /F "TOKENS=* USEBACKQ" %%F IN (`%MAKE_PROG% %MAKE_FILE_FLAG% Makefile.win %MAKE_TARGET%`) ^
          DO @ECHO ROCKSPEC=%%F>>%GITHUB_ENV%

      - name: Lint (Unix)
        if: runner.os != 'Windows'
        run: luarocks lint "$ROCKSPEC"

      - name: Lint (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: luarocks lint "%ROCKSPEC%"

      - name: Build (Unix)
        if: runner.os != 'Windows'
        run: luarocks make "$ROCKSPEC"

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: luarocks make "%ROCKSPEC%"

      - name: Test (Unix)
        if: runner.os != 'Windows'
        run: |
          for f in samples/*.lua; do
            echo "Running sample: ${f}";

            lua "${f}" || {
              echo "Failed to run the sample: ${f}";
              exit 1;
            }
          done

      - name: Test (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          FOR %%F IN (samples\*.lua) DO (
            ECHO Running sample "%%F"
            lua "%%F"

            IF %ERRORLEVEL% NEQ 0 (
              ECHO Failed to run the sample: %%F
              EXIT /B 1
            )
          )

  test-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - 5.5
          - luajit
          - openresty

        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        toolchain:
          - msvc
          - cc

        exclude:
          - os: ubuntu-latest
            toolchain: msvc

          - os: macos-latest
            toolchain: msvc

    env:
      TOOLCHAIN: ${{ matrix.toolchain }}

    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install -y uuid-dev

      - name: Setup MSVC
        uses: step-security/msvc-dev-cmd@22c98154b708dbd743e6f27a933cf6ceba3305c4 # v1.31.1
        if: runner.os == 'Windows' && matrix.toolchain == 'msvc'

      - name: Setup Lua and LuaRocks
        uses: luau-project/setup-lua@ebdc724769a3976b27abe70d93a730aede440ba9 # v2.0.8
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Configure (Unix)
        if: runner.os != 'Windows'
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DLUA_UUID_ENABLE_TESTS=ON \
            --install-prefix "$GITHUB_WORKSPACE/.lua" \
            -S . \
            -B build

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          IF "%TOOLCHAIN%" EQU "msvc" (
            SET "CMAKE_GENERATOR=NMake Makefiles"
          ) ELSE IF "%TOOLCHAIN%" EQU "cc" (
            SET "CMAKE_GENERATOR=MinGW Makefiles"
          ) ELSE (
            ECHO Unknown matrix.toolchain: %TOOLCHAIN%
            EXIT /B 1
          )

          cmake ^
            -G "%CMAKE_GENERATOR%" ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DLUA_UUID_ENABLE_TESTS=ON ^
            --install-prefix "%GITHUB_WORKSPACE%\.lua" ^
            -S . ^
            -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: ctest --test-dir build -C Release

      - name: Install
        run: cmake --install build --config Release

  test-multiple-compilers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - 5.5
          - luajit
          - openresty

        toolchain:
          - g++
          - clang
          - clang++

        exclude:
          - lua-version: luajit
            toolchain: g++

          - lua-version: openresty
            toolchain: g++

          - lua-version: luajit
            toolchain: clang++

          - lua-version: openresty
            toolchain: clang++

    env:
      TOOLCHAIN: ${{ matrix.toolchain }}

    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies
        run: sudo apt install -y uuid-dev

      - name: Install Clang
        if: contains(matrix.toolchain, 'clang')
        run: sudo apt install -y clang

      - name: Setup Lua and LuaRocks
        uses: luau-project/setup-lua@ebdc724769a3976b27abe70d93a730aede440ba9 # v2.0.8
        with:
          lua-version: ${{ matrix.lua-version }}
          cc: ${{ matrix.toolchain }}
          ld: ${{ matrix.toolchain }}

      - name: Set environment variable to hold the rockspec name
        run: |
          if test "$GITHUB_REF_TYPE" = "tag"; then
            echo "ROCKSPEC=$(make -f Makefile.unix echo-rockspec)" >> $GITHUB_ENV
          else
            echo "ROCKSPEC=$(make -f Makefile.unix echo-dev-rockspec)" >> $GITHUB_ENV
          fi

      - name: Lint
        run: luarocks lint "$ROCKSPEC"

      - name: Build
        run: luarocks make "$ROCKSPEC"

      - name: Test
        run: |
          for f in samples/*.lua; do
            echo "Running sample: ${f}";

            lua "${f}" || {
              echo "Failed to run the sample: ${f}";
              exit 1;
            }
          done

  test-cygwin:
    runs-on: windows-latest

    defaults:
      run:
        shell: D:\cygwin\bin\bash.exe --login -eo pipefail -o igncr '{0}'

    env:
      CYGWIN_NOWINPATH: 1
      CHERE_INVOKING: 1

    steps:

      - name: Change autocrlf to input
        shell: cmd
        run: git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Cygwin
        uses: cygwin/cygwin-install-action@3f0a3f9f988f7e96b8c18098ae05eaec175f5b52 # v6
        with:
          platform: x86_64
          packages: |
            coreutils
            wget
            gcc-g++
            make
            lua
            liblua-devel
            unzip
            libuuid-devel

      - name: Setup LuaRocks
        run: |
          luarocks_version="3.13.0"
          luarocks_url="https://luarocks.github.io/luarocks/releases/luarocks-${luarocks_version}.tar.gz"

          wget -P/tmp "${luarocks_url}" || {
            echo "Failed to download LuaRocks ${luarocks_version}";
            exit 1;
          }

          tar -C /tmp -xf "/tmp/luarocks-${luarocks_version}.tar.gz" || {
            echo "Failed to extract LuaRocks ${luarocks_version}";
            exit 1;
          }

          cd "/tmp/luarocks-${luarocks_version}" && \
          sed \
            -e "s|SHEBANG = .*|SHEBANG = \\\#\!/bin/env lua|" \
            -i GNUmakefile || {
            echo "Failed to patch GNUmakefile";
            exit 1;
          }

          ./configure --prefix=/usr && make && make install || {
            echo "Failed to configure, build or install LuaRocks ${luarocks_version}";
            exit 1;
          }

          echo 'eval $(luarocks path)' >> /etc/profile.d/luarocks.sh

      - name: Set environment variable to hold the rockspec name
        run: |
          if test "$GITHUB_REF_TYPE" = "tag"; then
            echo "ROCKSPEC=$(make -f Makefile.unix echo-rockspec)" >> $GITHUB_ENV
          else
            echo "ROCKSPEC=$(make -f Makefile.unix echo-dev-rockspec)" >> $GITHUB_ENV
          fi

      - name: Lint
        run: luarocks lint "$ROCKSPEC"

      - name: Build
        run: luarocks make "$ROCKSPEC"

      - name: Test
        run: |
          for f in samples/*.lua; do
            echo "Running sample: ${f}";

            lua "${f}" || {
              echo "Failed to run the sample: ${f}";
              exit 1;
            }
          done
